const authTypes = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  GET_USER: "GET_USER",
}

const alertTypes = {
  SHOW_ALERT: "SHOW_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
}

const userTypes = {
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",
  PATCH_USER_SUCCESS: "PATCH_USER_SUCCESS",
  PATCH_USER_FAILURE: "PATCH_USER_FAILURE",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
}

// Tags
const tagTypes = {
  GET_TAGS_SUCCESS: "GET_TAGS_SUCCESS",
  GET_TAGS_FAILURE: "GET_TAGS_FAILURE",
}

const userTagTypes = {
  DELETE_USER_FROM_TAG_SUCCESS: "DELETE_USER_FROM_TAG_SUCCESS",
  DELETE_USER_FROM_TAG_FAILURE: "DELETE_USER_FROM_TAG_FAILURE",
  ADD_USER_TO_TAG_SUCCESS: "ADD_USER_TO_TAG_SUCCESS",
  ADD_USER_TO_TAG_FAILURE: "ADD_USER_TO_TAG_FAILURE",
}

export { authTypes, alertTypes, tagTypes, userTagTypes, userTypes }
